ALTER DATABASE Model SET ANSI_NULLS ON
GO
ALTER DATABASE Model SET ANSI_PADDING ON
GO


ALTER DATABASE Model SET  ALLOW_SNAPSHOT_ISOLATION ON
GO

--requires no other active connections to named db
ALTER DATABASE Model SET READ_COMMITTED_SNAPSHOT ON
GO